server:
  host: localhost
  port: 8081
  mode: debug
db:
  driver: mysql
  host: localhost
  port: 3306
  user: root
  password: xiaohan1234
  dbname: ecommerce_db
  charset: utf8m4


redis:
  host: localhost
  port: 6379
  password : ""

jwt:
  symmetrickey: 12345678123456781234567812345678
  duration: 144h

alipay:
  appid: 9021000126639558
  privatekey: MIIEpAIBAAKCAQEA3JXvA8tpCvpPb16i7z7Jy5ShYDz3uABsOXT+vOQ+Mg2JyN8FfBRB9TPWv5kUpJ6cb08FJOI6vfErgKuna4Qajf3J9NukgFjAVu+WnvC11PYWmUsm5+CEdPdZtlx7McEnFnsvDOA9jrgGkH0UZctORZcBDPZRJbhi8GGEBJz1jMk0At6sEjQE+Laz0ka+IUllotpXw/dJ91lqtOIiX/SblpcD+98/vIdF5EcerF2Ch0LqWFfOJ4VcgpW7MFv7agdj4WI6bTDaT61qW+g4jjDjYm0dWSiVJqWrbpPzCMTIhPbHTt6TkCl7KO5u5LyW5Vrspua4t/Y1etw04u7wfnK1qQIDAQABAoIBAHgUNpS+OmR7dpqNzeynJXrpYh/dkIxdzoxIoBN7vE/LBuKOZZHyBSXSHmkWkCI9JbOCNK6raIbVrnTQ/MaOl1YMfdAJcTddGPc6XagQKSvQ+uRgAMHhermhnPikx3uCRiD61dYQi/IRQ6GMNXpkfitr1GqV+/6orVNmAlPwjcshCV2rPZVn36Ij7+HGarbfkVAkBhzqB/PioTySzyE6HcHHG0YDFWXEXBeHMX13jwhF3mrSw9vByw9kH83KnFd5yiJ//dOz8bywsXWkFTxHNlYYVqZtFlv3qaWF9NXbXdwsMibfAxPmZzIqbyAuJ2ga7m2lqkzVhJyHIN9mdV5r7jECgYEA+fGI3ajvzIJ6aKizZ8tkHzuuDouX0Lxvwen9sU+guc0ie+H2laJpbwePcB1KqQyQZ+51HDwaOlQXwV0kpUC2RU27R+t/b//00OtMOHRZgJkstl0gog+meuCW+2owQTtzmewYhvKcvlziJ8LihvyFKAhYDUzTsQm72ceL2x2WMFcCgYEA4e5I5Tmqte+YCrZf9K3wd77DpfO+W9MiOXXRJ9BlzL+h9ej0Jlmm4bZu4mQvJZmpP3HxSRQ403hZpNni9r0I5EeEYwYOt7fdslZOe3Z9nRJ0ASfrYnpLPYxpj8YwRY+lsKZ5oObYk6IZ/Q9xs6vag7ffWnzJ0L91Rv80qmWWif8CgYEAkIfcFhlfeUomEKkk/Ss+3VS8ZMrR4jFlCqQNQGAEWAzIGQzkc0i0YTDk//bgOnr6ci8Q51/V5s7D4dvDmg+eltrJJmCGk7RV1A2MSMT3EIcCtP2LJkuYgEuo4v9XohEH2wUMddSLUQUS/d0S8u3I7gpNKHu5mhE/4EIknHMyawcCgYEAtZEFzBG3+1Z9Xb6LBtvycIlCOk/UH39h9cOVPuXfqdgnlLSN4XQTBTnTiuTwbss6lN5BBnXV5TzG7hCcsaXhS3OeFOZ9VW/SHsv1bosfD+gQig1GwXF+ngwFmaGwkXaLtZdUD9b1HlAbip+qxLXLeid+u/2lQrlayp+192qEvIkCgYAd3uqxZcw0kGJGIuInt8t7WFD4GqQYehS5jdHe//mnZfqqj6M+OOI0A9aCiKHH9gB55PJfSE6ZX6YbPW4KmCSOUiTuAIx+Qj1BiH6DeR/08MtnP0sc+BS3Bt6yYwhbMMgIl1JUcSmhER3iSiVK4jvQpLIjPfXF66CNPzkFSqz5Hg==
  alipaypublickey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlG5owETwaakWHNwUaOx8qceXrR5jszQnaY5yApdHiLbSWqJ6mQvCaIDOYFDRX1uA6976Ih9uftRCYoQ5KbQh7y+vvwrKNc5DuXQkf0pLR4RPVGnJsgFsX+eBX3Md7o3m3K6WY66ewH9ScUyuLr3rGhxW81hFepof4GEQ6S8BpzMV0juTTdy56oXNV5GYnzoslLOAPsp/eaN0U1e9QUfm6yakygZFGymOt0bKElxEg/Bp3WYuf7NOM7zUnWtoGqummKRkv+0IMpm+xJWKtQWey3HGjqB6IGax+ulMSzwAIzmW+8ylYKekldkZ88HdY32HSH5+zH4EIgGwb9VDb2dnuwIDAQAB